# Generated by Django 6.0.7 on 2026-07-20 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
